version: '3'

services:
  consulserver01:
    image: consul:1.10
    container_name: consulserver01
    hostname: consulserver01
    command: ["consul", "agent", '-config-dir', "/etc/consul.d"]
    networks:
      - consul
    ports:
      - "8500:8500"
    volumes:
      - ./servers/server01:/etc/consul.d

  consulserver02:
    image: consul:1.10
    container_name: consulserver02
    hostname: consulserver02
    command: ["consul", "agent", '-config-dir', "/etc/consul.d"]
    networks:
      - consul
    volumes:
      - ./servers/server02:/etc/consul.d

  consulserver03:
    image: consul:1.10
    container_name: consulserver03
    hostname: consulserver03
    command: ["consul", "agent", '-config-dir', "/etc/consul.d"]
    networks:
      - consul
    volumes:
      - ./servers/server03:/etc/consul.d

  consulclient01:
    image: consul:1.10
    container_name: consulclient01
    hostname: consulclient01
    command: ["consul", "agent", '-config-dir', "/etc/consul.d"]
    networks:
      - consul
    volumes:
      - ./clients/consul01/config:/etc/consul.d
      
  consulclient02:
    image: consul:1.10
    container_name: consulclient02
    hostname: consulclient02
    command: ["consul", "agent", '-config-dir', "/etc/consul.d"]
    networks:
      - consul
    volumes:
      - ./clients/consul02/config:/etc/consul.d

networks:
  consul:
    driver: bridge
